# Generated by Django 5.2.4 on 2025-07-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='제목 없음', max_length=200),
        ),
    ]
